syntax = "proto3";

package zmk.core;

enum LockState {
    ZMK_STUDIO_CORE_LOCK_STATE_LOCKED = 0;
    ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED = 1;
}

message Request {
    oneof request_type {
        bool get_device_info = 1;
        bool get_lock_state = 2;
        bool lock = 3;
        bool reset_settings = 4;
        bool check_unsaved_changes = 5;
        bool save_changes = 6;
        bool discard_changes = 7;
    }
}

message Response {
    oneof response_type {
        GetDeviceInfoResponse get_device_info = 1;
        LockState get_lock_state = 2;
        bool reset_settings = 4;
        bool check_unsaved_changes = 5;
        SaveChangesResponse save_changes = 6;
        bool discard_changes = 7;
    }
}

message GetDeviceInfoResponse {
    string name = 1;
    bytes serial_number = 2;
}

message Notification {
    oneof notification_type {
        LockState lock_state_changed = 1;
    }
}

message SaveChangesResponse {
    oneof result {
        bool ok = 1;
        SaveChangesErrorCode err = 2;
    }
}

enum SaveChangesErrorCode {
    SAVE_CHANGES_ERR_OK = 0;
    SAVE_CHANGES_ERR_GENERIC = 1;
    SAVE_CHANGES_ERR_NOT_SUPPORTED = 2;
    SAVE_CHANGES_ERR_NO_SPACE = 3;
}
